const text7 = `
What was the hardest part of the college application process for you?
    For Dani, a student from Miami, Florida, the hardest part was the mental block. “I was constantly procrastinating. Hearing other people talk about it (the college process) would stress me out because I knew I was procrastinating and I just wanted to do things without other people commenting on the process 24/7.” The mental block and procrastination was exacerbated by other responsibilities in high school, since Dani had multiple extracurriculars, including being the vice president of the GSA, which she thinks boosted her application. She also struggled with coming up with ideas for the Common App essay, though in the end she wrote an essay she was proud of. 
    For Lucas, a student from Philadelphia, the struggle was in picking which schools to apply to. “Getting a feel for them online to see if I should actually apply was a challenge.” To see if he would like the school, Lucas would look up campus walkthroughs and Tiktoks to see what the school was like. 
    For Lily, a student from the suburbs of Philadelphia, the most difficult part was the college essay. “It goes to most every college so it has to be really versatile. Also sometimes it’s hard to write about yourself in a way that appeals to the college admissions people.”
    For me, the most difficult part was the SAT. Though many US schools were test optional, the ones in Europe were not, so I had to get a certain score, which was really hard for me. I do not perform well on standardized tests, but I still got the score I needed after taking the SAT twice. 

    What did you have to learn on your own about the college process?
    Dani says that there is a misconception about what colleges are looking for. “You should apply to schools even if you don’t think you have a chance. I feel like schools aren’t looking for the top students anymore, they’re looking for whoever is the best fit.” She believes that there is more to college applications than just being the best, that some schools might really like one thing on your application. “I got into NYU over so many other students who were more qualified on paper than me.” Dani would tell students not to discount possible schools just because they think they are out of their range. 
    Lucas says that learning about how to advertise extracurriculars on the Common App was something he had to do on his own; “Like what to say about them to make them look good.” He also wishes there was more support for applying to international schools; “It was too confusing so I gave up.” 
    Lily says that she had to learn how to present herself on paper. “I had to learn how to take personal things and make them professional.” This manifested mainly in both the essays and the questions the college asked, which was perhaps why Lily struggled with these things. 
    From my own experience I agree that applying internationally is something you largely have to do yourself. There wasn’t a lot of information about how to do it, and what to do. It’s also a completely different system from the US schools, and the framework for applying is also different. I got over this with help from my sister, who goes to school in England, and online resources. Luckily you can learn pretty much everything online. 

    What extracurriculars do you think added the most to your application?
    Dani says that being the vice president of the GSA definitely added a lot. She was also the outreach coordinator for the literary magazine. “Also just being part of clubs that weren’t easy to get into. Like the National Honors Society– you had to do certain things to be in it. And this health club I had to interview for. We would present every two weeks to the freshman and teach them things.” 
    For Lucas, the best thing for his college resume was orchestra, because he did it all four years of high school. He plays bass. He also did rowing, but says that it was less of a boost to his application since he only did it for junior year. 
    Lily’s school did not have many extracurriculars, though she was a mentor in the writing center. The writing center at her school allowed students to mentor other students on their writing assignments, though there was not a lot of student life or clubs besides that. Student mentorship is good for college applications because it shows that you care about other students and are actively engaged in the student bo– get quote
    In my experience, I think the school newspaper helped a lot with my application. I also did a summer abroad program in Amsterdam, which I think is something colleges like to see. I also added optional classes that I chose to take to make my application better, like a Queer History class. The extracurriculars reveal your interests and how you take those interests into the real world. 

    When did you seriously start thinking about college applications?
    Everyone (Dani, Lucas, Lily, and I) all started thinking seriously about college applications at the end of junior year. Dani said that it was when people really started talking about it, spurring her into action. It was the same for me. I thought college was further off than it was, so I didn’t start thinking about college until my peers started talking about it, during the spring of junior year. Then I visited some colleges that April and started studying for the SAT. I took an SAT that summer, and I know a lot of other kids did as well, then I retook it in the fall. I didn’t start my college essay until September, and finished it in early October. But some people start thinking about it earlier and some people start thinking about it later. 

    Did you have any extra college help outside of your college counselor?
    Dani’s school had a college readiness program during the last few weeks of junior year which helped. She also did SAT tutoring once but decided that it wasn’t worth the money. 
    Lucas got some SAT prep courses from his rowing team, made possible through donations. It was one class a week for five sessions through his junior year, and they were also given the official SAT study guide. 
    Lily barely had a college counselor, but got some help from her mom. 
    My parents did get me an SAT course because I needed a lot of help, but I don’t think it boosted my score much, though, since I never could get above a 1290. I also did practice tests on my own. Other than that it was a lot of stuff to figure out on my own. 

    What did you write your college essay on and why?
    Dani’s college essay was on her relationship with her tics and how she got over being embarrassed of them. “I feel like college admissions advisors want people to write about something weird and connect it to themselves, but sometimes you can just tell your story and that’s enough.” 
    Lucas wrote his essay on his love for science and how it is a cornerstone of who he is. “I think passion for science is what makes a good scientist and it’s something you can’t manufacture, like you can always study harder and do more problems but you can’t force yourself to love science.” He cites his love for science as the reason he is going to college. 
    Lily wrote her college essay on her interest in art and biology and how they intersected when she was kid playing in her grandparents backyard. She says there wasn’t much of a thought process behind it, more of “spontaneous combustion,” but that she wanted to write about something interesting that was unique to her. This is a good essay because it shows how your interest in a subject has evolved over time. 
    I wrote my college essay on my interest in witchcraft. It is one of my most unique interests, and I wanted to spin it in such a way that academic college admissions officers wouldn’t think I was, you know, crazy. I think I did a pretty good job explaining it in a science-y way. I chose this topic because I thought it would make me stand out, though at the time I also thought it was a little risky. 
`;

export default text7; 