const text2 = `
    “Why are you interested in ____ College or University?”
    
    College supplemental essays are very difficult for many students. The questions are often annoyingly open-ended, and the word counts even smaller than the Common App essay. Thus, students must fit more information in less space, squeezing in both an argument about why they are the best candidate for the university and an argument about why the university is the best candidate for them.
    
    Writing supplemental essays was one of the most difficult parts of the college process for me, even though I love writing. I struggled with fitting everything in so few words, especially since there seemed to be so many topics I had to hit. I felt like I had to discuss why I wanted to go to that university, how I would best use their resources, why I was a good fit for them, and to brag about my own achievements, something that has never come naturally to me. In retrospect, I chose the wrong things to focus on.
    
    I faced my anxieties about college supplemental essays when applying to colleges in the UK rather than America. There, they use a system called UCAS (The Universities and Colleges Admissions Service) where you apply directly to your major, rather than the college in general. While perhaps more stressful, this was helpful when writing my UCAS personal statement. It allowed me to zero in on what I actually had to brag about, which, in my case, was history. The framework for UCAS allowed me to create a story, a narrative about my interest in history and build my personality around that. I realized that every interest, every hobby I had had some of me in it, and I just had to build that in. I grew a lot through writing my supplemental essays, and there is a marked improvement in the essays I wrote later in the college process. By the time I began the UCAS essay I had learned a lot about the process and was better at selling myself, making it one of the best college essays I wrote (in my opinion). 
    
    The word count is still especially challenging, but it is important to focus on your goals and how the school that you are applying to can get you closer to those goals. These goals should illuminate your personality, letting admissions counselors know who you are. Show them that you are a driven student. I made the mistake of focusing too much on the location of the universities because that was important to me, which I think detracted from my application. Since you have very few words, it is crucial that you get to the point and not waste time. How have your previous successes led to where you are now? What are your goals, and how does this school align with them? Think about the way the school is evolving, how it is changing– does that align with your dreams as well? How does what you want align with the goals of the college (some colleges state their goals in the prompts). Once again, it is important not to regurgitate things on the college website, but rather to expand on what they have in order to reveal who you are as a person. Writing these essays is almost an exercise in thinking, because you have to start asking the right questions about yourself and what you want. 
    
    You should also try to subtly put your own achievements in your essay in a way that is natural. Everyone has something they are proud of, whether it be school or an extracurricular, and it is important that your college of choice knows that too. Though it may feel awkward to brag about your achievements (it was for me), it is an important skill to have, whether it be in college applications or job cover letters. This was something I just had to get over when doing my college essays, because you are never going to move past marketing yourself– it’s what modern success is all about. 
    
    There are a lot of other resources online with questions that can prompt you thinking in the right directions. These colleges know who they are, but want to know who you are. 
`;

export default text2;