const text4 = `
    Creating a college list is a fundamental part of the college process, but can be difficult because there are so many colleges to choose from. Luckily, there are a lot of resources online about reach and safety schools. But everyone’s preferences are different, so, in the end, your college list depends on what you personally want in a school. 
	
    The first thing is the accessibility of the school to you, so finding your reach, target, and safety schools. Your reach school is a dream school that is highly competitive and accepts fewer applicants. If your grades and test scores are below the average acceptance, that school is a reach. Usually it is somewhere that you have less of a chance getting into. It is good to have a few reach schools in your college list, maybe 2 or 3. A target school is a school that accepts students like you— your grades and test scores match, it’s a more accessible and less competitive. It is a good idea to have about 4 target schools in your college list. A safety school is a school that you have a good chance of being accepted at. It has a high acceptance rate and accepts students with lower scores than you. You should apply to at least two safeties. 
	
    This can help you compile a basic college list. After that you can narrow it down based on what you want. Especially with my experience in applying to European and UK schools, where each university has a different school for each major, the ranking for History mattered a lot. What schools are best for your chosen field? Even though a school might be really good on paper, it will not help you if it’s really good in the sciences but not in the arts, or vice versa. It is important to look at what programs the school puts resources into so you can make sure you aren’t applying somewhere that doesn’t fund the major you want to study. Not everywhere is going to be good for your major. Some majors are also more competitive at certain schools. 
	
    There is also an economic element. What schools have a lot of scholarships? What schools are need-blind, meaning they do not consider financial need in acceptances? At need-aware colleges, admissions officers may consider a student's ability to pay when choosing which student to accept. Some people chase merit, which means they compile their college list based on what places have merit scholarships. 
	
    After this helps you narrow it down, you can rely on your own parameters. For me, location mattered a lot. I wanted to be in a city, so any schools that were in rural areas were rated lower on my list or crossed off altogether. I wanted to be at a large school as well, so smaller schools were rated lower. I wanted a school that would be LGBTQ-friendly. This is very personal to you. Where do you think you could thrive the most? What kind of education style do you prefer? Where do you want to be locationally?
	
    At this point you probably should have a decently sized college list. Not every college has to be perfect, but you should still apply to about 5-12 schools. There are a lot of college search engines that you can use to find places to apply to. These websites have filters that can help you find schools that fit your parameters. They can also tell you how you compare to the current student population to show whether it is a reach, safety, or target. So poke around a bit and see what you find!
`; 

export default text4;